#pragma once
#include <WinUser.h>

#include "f4se/ScaleformMovie.h"
#include "f4se/ScaleformValue.h"

void SetGFxValue(GFxValue* dst, GFxMovieRoot* root, const char* name, const char* str);
void SetGFxValue(GFxValue* dst, GFxMovieRoot* root, const char* name, std::string str);
void SetGFxValue(GFxValue* dst, const char* name, GFxValue value);
void SetGFxValue(GFxValue* dst, const char* name, UInt32 value);
void SetGFxValue(GFxValue* dst, const char* name, double value);
void SetGFxValue(GFxValue* dst, const char* name, bool value);
void SetGFxValue(GFxValue* dst, const char* name, int value);

enum ScanCodes {
    kScanCode_BACKSPACE   = 0x08,
    kScanCode_TAB         = 0x09,
    kScanCode_ENTER       = 0x0D,
    kScanCode_ESCAPE      = 0x1B,
    kScanCode_SPACE       = 0x20,
    kScanCode_LEFT        = 0x25,
    kScanCode_UP          = 0x26,
    kScanCode_RIGHT       = 0x27,
    kScanCode_DOWN        = 0x28,
    kScanCode_0           = 0x30,
    kScanCode_1           = 0x31,
    kScanCode_2           = 0x32,
    kScanCode_3           = 0x33,
    kScanCode_4           = 0x34,
    kScanCode_5           = 0x35,
    kScanCode_6           = 0x36,
    kScanCode_7           = 0x37,
    kScanCode_8           = 0x38,
    kScanCode_9           = 0x39,
    kScanCode_A           = 0x41,
    kScanCode_B           = 0x42,
    kScanCode_C           = 0x43,
    kScanCode_D           = 0x44,
    kScanCode_E           = 0x45,
    kScanCode_F           = 0x46,
    kScanCode_G           = 0x47,
    kScanCode_H           = 0x48,
    kScanCode_I           = 0x49,
    kScanCode_J           = 0x4A,
    kScanCode_K           = 0x4B,
    kScanCode_L           = 0x4C,
    kScanCode_M           = 0x4D,
    kScanCode_N           = 0x4E,
    kScanCode_O           = 0x4F,
    kScanCode_P           = 0x50,
    kScanCode_Q           = 0x51,
    kScanCode_R           = 0x52,
    kScanCode_S           = 0x53,
    kScanCode_T           = 0x54,
    kScanCode_U           = 0x55,
    kScanCode_V           = 0x56,
    kScanCode_W           = 0x57,
    kScanCode_X           = 0x58,
    kScanCode_Y           = 0x59,
    kScanCode_Z           = 0x5A,
    kScanCode_LWIN        = 0x5B,
    kScanCode_RWIN        = 0x5C,
    kScanCode_PAD_0       = 0x60,
    kScanCode_PAD_1       = 0x61,
    kScanCode_PAD_2       = 0x62,
    kScanCode_PAD_3       = 0x63,
    kScanCode_PAD_4       = 0x64,
    kScanCode_PAD_5       = 0x65,
    kScanCode_PAD_6       = 0x66,
    kScanCode_PAD_7       = 0x67,
    kScanCode_PAD_8       = 0x68,
    kScanCode_PAD_9       = 0x69,
    kScanCode_PAD_MUL     = 0x6A,
    kScanCode_PAD_ADD     = 0x6B,
    kScanCode_PAD_SUB     = 0x6D,
    kScanCode_PAD_DEC     = 0x6E,
    kScanCode_PAD_DIV     = 0x6F,
    kScanCode_F1          = 0x70,
    kScanCode_F2          = 0x71,
    kScanCode_F3          = 0x72,
    kScanCode_F4          = 0x73,
    kScanCode_F5          = 0x74,
    kScanCode_F6          = 0x75,
    kScanCode_F7          = 0x76,
    kScanCode_F8          = 0x77,
    kScanCode_F9          = 0x78,
    kScanCode_F10         = 0x79,
    kScanCode_F11         = 0x7A,
    kScanCode_F12         = 0x7B,

    // Gamepad Specific
    kScanCode_GP_UP       = 0x0001,
    kScanCode_GP_DOWN     = 0x0002,
    kScanCode_GP_LEFT     = 0x0004,
    kScanCode_GP_RIGHT    = 0x0008,
    kScanCode_GP_START    = 0x0010,
    kScanCode_GP_BACK     = 0x0020,
    kScanCode_GP_LTH      = 0x0040,
    kScanCode_GP_RTH      = 0x0080,
    kScanCode_GP_LSH      = 0x0100,
    kScanCode_GP_RSH      = 0x0200,
    kScanCode_GP_A        = 0x1000,
    kScanCode_GP_B        = 0x2000,
    kScanCode_GP_X        = 0x4000,
    kScanCode_GP_Y        = 0x8000,
};